/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        primary: "#007AFF",
        "primary-light": "#e8e8fd",
        "bg-light": "#ffffff",
        "bg-secondary": "#F2F2F7",
        "bg-chat": "#ffffff",
        "nav-light": "#f9f9f9",
        "border-light": "#e5e7eb",
        divider: "#F2F2F2",
        "text-main": "#1C1C1E",
        "text-muted": "#6b7280",
        "text-hint": "#8E8E93",
        "ios-green": "#e7f8e8",
        "ios-green-text": "#1a4d2e",
        "ios-gray": "#F2F2F7",
        "bubble-user": "#e7f8e8",
        "bubble-ai": "#ffffff",
        "tag-reasoning": "#FFF8E1",
        "tag-reasoning-text": "#FF6F00",
        "tag-vision": "#E8F5E9",
        "tag-vision-text": "#1B5E20",
        "tag-tools": "#F3E5F5",
        "tag-tools-text": "#4A148C",
        "tag-coding": "#E8EAF6",
        "tag-coding-text": "#1A237E",
        "tag-context": "#FFF3E0",
        "tag-context-text": "#E65100",
        "accent-green": "#34C759",
        success: "#34C759",
        warning: "#f59e0b",
        error: "#ef4444",
      },
      fontFamily: {
        display: ["Inter"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
